### ISSUE TITLE
Doesnt apply a config

### ISSUE THREAD

**Issue by pr0phe** [dokmic/chuangmi-camera-v5#1]
Ive got cn cam version, after sucsess flashing it doesn't start rstp and doesn't appy a config placed in root of sd

MQTT=1
MQTT_HOST="192.168.31.16"
MQTT_PASSWORD='mqtt'
MQTT_PORT="1883"
MQTT_USER='mqtt'

**Comment by dokmic** [comment]
Hey, @pr0phe!

- Did your `confg.cfg` get renamed to `config.cfg.bak`?
- Were you able to see your camera in the Mi Home app?
- What firmware version do you see in the Mi Home app right after the flashing?

**Comment by pr0phe** [comment]
totaly, ive found another cam (previous at another place, ill try it later).
symptoms at least:
1. flash - sucsess
2. config apply - sucsess
3. rtsp - fail as well as mqtt (disabled for current logs)

logs in attach
[messages.log](https://github.com/dokmic/chuangmi-camera-v5/files/11731665/messages.log)
current firmware 3.3.6_2018062014
and it asks to update to 3.3.6_2018072417

//upd: after fw update and few reboots rtsp sucsessfully starts, one problem with mqtt for that cam.
ive got a few some, will try in them too. 
could you pls provide with sample of mqtt config, i thing i mesed with ' and " 

also troubles with rstp authorization:
i ve tried to spec in config
RTSP_PASSWORD="12345"
RTSP_USER="admin"
//
RTSP_PASSWORD=12345
RTSP_USER=admin
//
RTSP_PASSWORD='12345'
RTSP_USER='admin'

it doesn't work, its ok only when i havent spec anything for user and pwd
For RTSP_PASSWORD="12345"
RTSP_USER="admin"
i see in logs:
Jan  1 08:00:37 rtspd[794]: Stream username: admin^M
Jan  1 08:00:37 rtspd[794]: Stream password: 12345^M
but they do not comply too

**Comment by dokmic** [comment]
Hey, @pr0phe!

From the logs I see that the MQTT client isn't enabled.
```
Jan  1 08:00:16 firmware: NTP client is enabled.
Jan  1 08:00:17 firmware: Cloud services are enabled.
Jan  1 08:00:17 firmware: Stopping MQTT service.
Jan  1 08:00:17 firmware: MQTT is disabled.
Jan  1 08:00:18 firmware: Stopping automatic night mode.
Jan  1 08:00:18 firmware: Automatic night mode is disabled.
Jan  1 08:00:19 firmware: OTA is enabled.
Jan  1 08:00:19 firmware: RTSP is enabled.
Jan  1 08:00:20 firmware: Streamer is enabled.
```

That's probably because the config is malformed. It expects `1`, but in your case it's probably `1^M`. Here is the hint:
```
Jan 1 08:00:37 rtspd[794]: Stream username: admin^M
Jan 1 08:00:37 rtspd[794]: Stream password: 12345^M
```

I guess you are on Windows, where `CRLF` is used by default for line breaks. Could you try to use some other editor where you can configure line breaks and use Unix-like breaks (`LF`)?

As soon as you fix it, the MQTT client should be enabled along with the RTSP authorization. By the way, `STREAMER` should be disabled in order to have a stable RTSP stream.

**Comment by pr0phe** [comment]
cute! it works! second live of my old mi cams! thank a lot
